spring.data.mongodb.uri=${MONGODB_URI}

app.allowed.origin=${ALLOWED_ORIGIN}

spring.output.ansi.enabled=always

app.mail.from=${MAIL_FROM}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.root=INFO

spring.data.mongodb.auto-index-creation=true

server.port=${PORT:8080}